services:

  mongo:
    image: mongo:6.0.8
    container_name: todo-tdd-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-todo-tdd-db:/data/db
      - mongo-todo-tdd-db-config:/data/configdb

  mongo-express:
    container_name: todo-tdd-admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

volumes:
  mongo-todo-tdd-db:
  mongo-todo-tdd-db-config: